library(shiny)

shinyServer(
  function(input,output){
      
    output$url<-renderUI({
      
      foodType <- input$type
      optionType <- input$option
      
      if(foodType=="Malay" && optionType=="Food")
        text<-list(
              h4(
              tags$a(href="https://www.allrecipes.com/recipe/78938/malaysian-nasi-lemak/","Nasi Lemak"),
              br(),
              img(src = "nasi lemak.jpg",width="200px",height="200px"),
              br(),
              br(),
              tags$a(href="http://vivianpangkitchen.blogspot.my/2013/03/mee-bandung-bandung-noodles-mff-johor.html#.WvkbMExuLIU","Mee Bandung"),
              br(),
              img(src="mee bandung.jpg",width="200px",height="200px"),
              br(),
              br(),
              tags$a(href="http://www.malaysiarice.com/index.php/en/recipes/dessert/item/ketupat","Ketupat"),
              br(),
              img(src="ketupat.jpeg",width="200px",height="200px"),
              br(),
              br(),
              tags$a(href="https://cookpad.com/us/recipes/3312572-malaysian-biryani-rice-nasi-briyani","Nasi Briyani"),
              br(),
              img(src="nasi briyani.jpg",width="200px",height="200px"),
              br(),
              br(),
              tags$a(href="http://www.bite.co.nz/recipe/10979/Malaysian-satay-and-peanut-sauce/","Satay"),
              br(),
              img(src="satay.jpg",width="200px",height="200px"),
              br(),
              br(),
              tags$a(href="http://www.curiousnut.com/spicy-malaysian-grilled-fish/","Ikan Bakar"),
              br(),
              img(src="ikan bakar.jpeg",width="200px",height="200px"),
              br(),
              br(),
              tags$a(href="https://www.hungrygowhere.my/recipe/easy-malay-recipe-asam-pedas-ikan/28843101/","Asam Pedas"),
              br(),
              img(src="ikan asam pedas.jpg",width="200px",height="200px"),
              br(),
              br(),
              tags$a(href="http://keeprecipes.com/recipe/howtocook/nasi-kerabu","Nasi Kerabu"),
              br(),
              img(src="nasi kerabu.jpg",width="200px",height="200px"),
              br(),
              br(),
              tags$a(href="https://www.allrecipes.com/recipe/156939/spicy-tomato-chicken-ayam-masak-merah/","Ayam Masak Merah"),
              br(),
              img(src="ayam masak merah.jpg",width="200px",height="200px")))
     
      else if (foodType=="Malay" && optionType=="Kueh")
        text<-list(
              h4(
              tags$a(href="https://rasamalaysia.com/onde-onde-ondeh-ondeh/2/","Ondeh-ondeh"),
              br(),
              img(src="ondeh-ondeh.jpeg",width="200px",height="200px"),
              br(),
              br(),
              tags$a(href="https://rasamalaysia.com/seri-muka/2/","Seri Muka"),
              br(),
              img(src="seri muka.jpg",width="200px",height="200px"),
              br(),
              br(),
              tags$a(href="http://allrecipes.asia/recipe/9614/kuih-kosui.aspx","Kosui"),
              br(),
              img(src="kosui.JPG",width="200px",height="200px"),
              br(),
              br(),
              tags$a(href="https://malaysiandelicacies.blogspot.my/2008/01/kuih-puteri-ayu.html","Puteri Ayu"),
              br(),
              img(src="puteri ayu.jpg",width="200px",height="200px"),
              br(),
              br(),
              tags$a(href="https://www.nyonyacooking.com/recipes/kuih-koci","Kuih Koci"),
              br(),
              img(src="kuih koci.jpg",width="200px",height="200px"),
              br(),
              br(),
              tags$a(href="http://www.curiousnut.com/malaysian-peanut-pancake-turnover-apam-balik/","Apam Balik"),
              br(),
              img(src="apam balik.jpg",width="200px",height="200px"),
              br(),
              br(),
              tags$a(href="https://rasamalaysia.com/kuih-dadar-kuih-tayap/2/","Kuih Dadar"),
              br(),
              img(src="kuih dadar.jpg",width="200px",height="200px"),
              br(),
              br(),
              tags$a(href="http://luveenalee.com/kuih-bingka-pandan-kuih-bakar-pandan-malaysian-food-recipe/","Kuih Bingka Pandan"),
              br(),
              img(src="kuih bingka.jpg",width="200px",height="200px"),
              br(),
              br(),
              tags$a(href="https://rasamalaysia.com/roti-jala-recipe/2/","Roti Jala"),
              br(),
              img(src="roti jala.jpeg",width="200px",height="200px")))
      
      
      else if(foodType=="Chinese" && optionType=="Food")
        text<-list(h4(
          tags$a(href="https://www.wikihow.com/Cook-Chinese-Fried-Rice-in-Malaysian-Style","Chinese Fried Rice"),
          br(),
          img(src="chinese fried rice.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="http://sornascollection.blogspot.my/2011/05/chinese-steam-bun-pau.html","Pau"),
          br(),
          img(src="pau.jpg",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://noobcook.com/klang-bak-kut-teh/2/","Bak Kut Teh"),
          br(),
          img(src="bak kut teh.jpg",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="http://www.tofoodwithlove.com/2012/07/wonton-noodles-wantan-mee.html","Wanton Noodles"),
          br(),
          img(src="wanton mee.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://steamykitchen.com/5068-hainanese-chicken-rice.html","Hainan Chicken Rice"),
          br(),
          img(src="hainanese chicken rice.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://malaysiandelicacies.blogspot.my/2013/11/kung-pao-chicken.html","Kung Pao Chicken"),
          br(),
          img(src="kung pao chicken.jpg",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="http://www.mykitchensnippets.com/2011/06/hokkien-lor-meestew-noodles.html","Hokkien Lor Mee"),
          br(),
          img(src="hokkien lor mee.jpg",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://rasamalaysia.com/chicken-dumplings/2/","Dumpling"),
          br(),
          img(src="dumpling.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://rasamalaysia.com/chinese-tea-eggs-tea-leaf-eggs-recipe/2/","Tea Leaf Egg"),
          br(),
          img(src="tea leaf egg.png",width="200px",height="200px")))
      
      else if(foodType=="Chinese" && optionType=="Kueh")
        text<-list(h4(
          tags$a(href="https://rasamalaysia.com/angku-kuih-red-tortoise-cake/2/","Angku Kueh"),
          br(),
          img(src="angku kueh.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="http://chefwo.com/kuih-kapit-recipe/","Kuih Kapit"),
          br(),
          img(src="kuih kapit.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://rasamalaysia.com/popiah-fresh-spring-rolls/2/","Popiah"),
          br(),
          img(src="popiah.jpg",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="http://www.malaysiavegetarianfood.com/tag/chwee-kueh-recipe/","Chwee Kueh"),
          br(),
          img(src="chwee kueh.jpg",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="http://honestcooking.com/steamed-layer-cake-snack-recipe/","Kuih Lapis"),
          br(),
          img(src="kuih lapis.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="http://www.mykitchensnippets.com/2015/04/soon-kuehbangkwan-kuehjicama-dumplings.html","Soon Kueh"),
          br(),
          img(src="soon kueh.jpg",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="http://www.guaishushu1.com/a-chinese-steamed-cake-that-i-am-not-familiar-withhee-pan-or-xi-ban-???????????????%ef%bc%89/","Hee Pan"),
          br(),
          img(src="hee pan.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://www.malaysianchinesekitchen.com/kuih-bangkit-tapioca-cookies/","Kuih Bangkit"),
          br(),
          img(src="kuih bangkit.jpg",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="http://www.guaishushu1.com/teochew-png-kuih-revisited-????????????%EF%BC%89/","Teochew Kueh"),
          br(),
          img(src="teochew kueh.png",width="200px",height="200px")))
      
      else if(foodType=="Indian" && optionType=="Food")
        text<-list(h4(
          tags$a(href="http://www.geniuskitchen.com/recipe/roti-canai-authentic-malaysian-recipe-270723","Roti Canai"),
          br(),
          img(src="roti canai.jpg",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://www.tarladalal.com/Rice-and-Curry-in-Banana-Leaves-Banana-Leaf-Rice-7557r","Banana Leaf Rice"),
          br(),
          img(src="banana leaf.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="http://www.lilvienna.com/easy-no-yeast-naan/","Naan"),
          br(),
          img(src="naan.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://asianinspirations.com.au/recipe/putu-mayam-string-hoppers","Putu Mayam"),
          br(),
          img(src="putu mayam.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="http://www.friedchillies.com/articles/detail/making-masala-tosai-and-chutney","Tosai"),
          br(),
          img(src="tosai.jpg",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://rasamalaysia.com/tandoori-chicken/2/","Tandoori Chicken"),
          br(),
          img(src="tandoori chicken.jpg",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://www.sbs.com.au/food/recipes/malaysian-indian-salad-pasembur","Pasembur"),
          br(),
          img(src="pasembur.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://rasamalaysia.com/indian-chicken-curry/2/","Curry"),
          br(),
          img(src="curry.jpg",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="http://www.recipesaresimple.com/murtabak-recipe-with-chicken/","Murtabak"),
          br(),
          img(src="murtabak.png",width="200px",height="200px")))
      
      else 
        text<-list(h4(
          tags$a(href="https://www.vegrecipesofindia.com/moong-dal-halwa-recipe-halwa-recipes/","Moong Dal Halwa"),
          br(),
          img(src="moong dal halwa.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://food.ndtv.com/recipe-gulab-jamun-232943","Gulab Jamun"),
          br(),
          img(src="gulab jamun.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://food.ndtv.com/recipe-kaju-ki-barfee-100483","Kaju Ki Barfi"),
          br(),
          img(src="kaju ki barfi.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://www.vegrecipesofindia.com/kalakand-recipe-quick-kalakand-recipe/","Kalakand"),
          br(),
          img(src="kalakand.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://food.ndtv.com/recipe-gajar-halwa-sunehri-style-178266","Gajar Halwa"),
          br(),
          img(src="gajar halwa.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://www.vegrecipesofindia.com/motichoor-ladoo-recipe-motichur-laddu/","Motchichoor Ladoo"),
          br(),
          img(src="motchichoor ladoo.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://food.ndtv.com/recipe-sandesh-106796","Sandesh"),
          br(),
          img(src="sandesh.png",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://food.ndtv.com/recipe-modak-217982","Modak"),
          br(),
          img(src="modak.jpg",width="200px",height="200px"),
          br(),
          br(),
          tags$a(href="https://food.ndtv.com/recipe-shahi-tukda-with-pineapple-387491","Shahi Tukda"),
          br(),
          img(src="shahi tukda.png",width="200px",height="200px")))
          
        
        
    })
    
  }
)